export default {
  USER_ALREADY_EXISTS: 'Usuário já existe',
  USER_NOT_FOUND: 'Usuário não encontrado',
  PASSWORDS_MUST_MATCH: 'A confirmação de senha não bate com a senha',
  PASSWORD_TOO_WEAK: 'Senha muito fraca',
  OLD_PASSWORD_INCORRECT: 'A senha antiga não está correta',
  LOGIN_INVALID: 'O e-mail e/ou senha estão incorretos',
  LOGIN_CODE_EXPIRED: 'Código de login expirado',
  LOGIN_CODE_INVALID: 'Código de login inválido',
  FORGOT_PASSWORD_TOKEN_EXPIRED: 'Token Expirado',
  FORGOT_PASSWORD_TOKEN_INVALID: 'Token Inválido',
  SERVICE_UNAVAILABLE: 'Serviço indisponível',
  PERMISSION_ALREADY_EXISTS: 'Permissão já existe',
  PERMISSION_NOT_FOUND: 'Permissão não existe',
  ROLE_ALREADY_EXISTS: 'Cargo já existe',
  ROLE_NOT_FOUND: 'Cargo não existe',
  DEVICE_NOT_FOUND: 'Dispositivo não encontrado',
  CREDENTIALS_NOT_FOUND: 'Credencial não existe',
  INVALID_CREDENTIAL: 'Credencial inválida',
  MACADDRESS_DOES_NOT_MATCH: 'Mac Address inválido para o deviceId',
  FEATURE_SLUG_INVALID: 'Slug da feature inválida',
  FEATURE_NOT_FOUND: 'Feature não encontrada',
  PROVIDER_NAME_INVALID: 'Nome do Provider inválido',
  PAGE_MUST_BE_POSITIVE: 'Argumento page precisa ser no mínimo 1',
  PER_PAGE_MUST_BE_POSITIVE: 'Argumento per page precisa ser no mínimo 1',
  PER_PAGE_MAX: 'O Máximo para perPage é 50',
  EMPTY_PROVIDER: 'Nenhum provider selecionado',
  VTEX_KEYS_MISSING: 'Chaves VTEX faltando',
  VTEX_FORBIDDEN_BY_WHITELIST: 'Rota VTEX proibida',
  VTEX_FORBIDDEN_BY_ORDERFORM_USER_DIVERGENCE:
    'Usuário não é dono do orderform',
  VTEX_CLIENT_ERROR: 'Erro com vtex client',
  FORBIDDEN: 'Proibido',
  UNAUTHORIZED: 'Unauthorized',
  SKU_IN_WISHLIST_NOT_FOUND: 'Sku não favoritado',
  SKU_ALREADY_ON_WISHLIST: 'Sku já favoritado',
  SYNC_USER_DATA_WITH_VTEX:
    'Erro ao realizar o sync de dados do usuário no login:',
  AFFILIATE_NOT_FOUND: 'Afiliado não encontrado',
  LAVOURA_NOT_FOUND: 'Lavoura não encontada',
  TIPO_PRODUTO_NOT_FOUND: 'Tipo do produto não foi encontrado',
  CULTURA_NOT_FOUND: 'Cultura não foi encontrada',
  PRODUTO_NOT_FOUND: 'Produto não foi encontrado',
};
